- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
        region: "{{region}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: create public subnet 1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1cidr}}"
        map_public: yes
        ressource_tags:
          Name: vprofile-pubsub1
      register: pusub1_out
