- hosts: Ansible
  connection: local
  gather_facts: false
  tasks:
    - name: import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
        region: "{{region}}"
      register: vpcout

